### ISSUE TITLE
这是什么原因

### ISSUE THREAD

**Issue by Fihade** [MinusZoneAI/ComfyUI-TrainTools-MZ#4]
![image](https://github.com/MinusZoneAI/ComfyUI-TrainTools-MZ/assets/24598480/b0df36e2-6c12-420a-9b00-ccfe1da9d66a)

**Comment by wailovet** [comment]
报错往上拉拉,这是哪个节点爆出的

**Comment by Fihade** [comment]
> 报错往上拉拉,这是哪个节点爆出的

If execution seems broken due to forward ComfyUI changes, you can disable the optimization from rgthree settings in ComfyUI.
当前分支(current branch): 71e2c91330a9d866ec05cdd10584bbb962896a99(HEAD)
目标分支(target branch): 71e2c91330a9d866ec05cdd10584bbb962896a99
From https://githubfast.com/kohya-ss/sd-scripts
 * branch            71e2c91330a9d866ec05cdd10584bbb962896a99 -> FETCH_HEAD
HEAD is now at 71e2c91 Merge pull request #1230 from kohya-ss/dependabot/github_actions/crate-ci/typos-1.19.0
===========================httpd.serve_forever() start=======================================
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.3.0+cu121 with CUDA 1201 (you have 2.1.2+cu121)
    Python  3.10.14 (you have 3.10.13)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Traceback (most recent call last):
  File "/root/ComfyUI/custom_nodes/ComfyUI-TrainTools-MZ/hook_kohya_ss_run.py", line 38, in <module>
    import hook_kohya_ss_utils
  File "/root/ComfyUI/custom_nodes/ComfyUI-TrainTools-MZ/hook_kohya_ss_utils.py", line 120, in <module>
    original_snapshot_download = diffusers.loaders.single_file.snapshot_download
AttributeError: module 'diffusers.loaders.single_file' has no attribute 'snapshot_download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/ComfyUI/custom_nodes/ComfyUI-TrainTools-MZ/hook_kohya_ss_run.py", line 40, in <module>
    from . import hook_kohya_ss_utils
ImportError: attempted relative import with no known parent package
!!! Exception during processing!!! 训练失败!!! 具体报错信息请查看控制台... Command '['/conda/bin/python', '/root/ComfyUI/custom_nodes/ComfyUI-TrainTools-MZ/hook_kohya_ss_run.py', '--sys_path', '/root/ComfyUI/models/minus_zone_models/train_tools/kohya_ss_lora', '--train_config_json', '{"pretrained_model_name_or_path": "/root/ComfyUI/models/checkpoints/sd_xl_base_1.0.safetensors", "max_train_steps": "15", "xformers": true, "sdpa": false, "fp8_base": false, "mixed_precision": "fp16", "cache_latents": true, "cache_latents_to_disk": true, "network_dim": "16", "network_alpha": "8", "network_module": "networks.lora", "network_train_unet_only": true, "learning_rate": "1e-5", "lr_scheduler": "cosine_with_restarts", "optimizer_type": "AdamW", "save_every_n_epochs": "5", "shuffle_caption": true, "lr_warmup_steps": "0", "save_precision": "fp16", "lr_scheduler_num_cycles": "1", "persistent_data_loader_workers": true, "no_metadata": true, "noise_offset": "0.1", "output_dir": "/root/ComfyUI/output/mz_train_workspaces/KiKi/output", "output_name": "KiKi_lora_sdxl_20240626_182017", "no_half_vae": true, "lowram": false, "dataset_config": "/root/ComfyUI/output/mz_train_workspaces/KiKi/dataset.toml", "max_train_epochs": "100"}', '--train_func', 'run_lora_sdxl', '--master_port', '60992', '--other_config_json', '{"sample_prompt": "Anya"}']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/root/ComfyUI/custom_nodes/ComfyUI-TrainTools-MZ/mz_train_tools_core.py", line 416, in run_hook_kohya_ss_run_file
    subprocess.run(
  File "/conda/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/conda/bin/python', '/root/ComfyUI/custom_nodes/ComfyUI-TrainTools-MZ/hook_kohya_ss_run.py', '--sys_path', '/root/ComfyUI/models/minus_zone_models/train_tools/kohya_ss_lora', '--train_config_json', '{"pretrained_model_name_or_path": "/root/ComfyUI/models/checkpoints/sd_xl_base_1.0.safetensors", "max_train_steps": "15", "xformers": true, "sdpa": false, "fp8_base": false, "mixed_precision": "fp16", "cache_latents": true, "cache_latents_to_disk": true, "network_dim": "16", "network_alpha": "8", "network_module": "networks.lora", "network_train_unet_only": true, "learning_rate": "1e-5", "lr_scheduler": "cosine_with_restarts", "optimizer_type": "AdamW", "save_every_n_epochs": "5", "shuffle_caption": true, "lr_warmup_steps": "0", "save_precision": "fp16", "lr_scheduler_num_cycles": "1", "persistent_data_loader_workers": true, "no_metadata": true, "noise_offset": "0.1", "output_dir": "/root/ComfyUI/output/mz_train_workspaces/KiKi/output", "output_name": "KiKi_lora_sdxl_20240626_182017", "no_half_vae": true, "lowram": false, "dataset_config": "/root/ComfyUI/output/mz_train_workspaces/KiKi/dataset.toml", "max_train_epochs": "100"}', '--train_func', 'run_lora_sdxl', '--master_port', '60992', '--other_config_json', '{"sample_prompt": "Anya"}']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/root/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/root/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/root/ComfyUI/custom_nodes/ComfyUI-TrainTools-MZ/__init__.py", line 278, in start
    return mz_train_tools_core.MZ_KohyaSSTrain_call(kwargs)
  File "/root/ComfyUI/custom_nodes/ComfyUI-TrainTools-MZ/mz_train_tools_core.py", line 518, in MZ_KohyaSSTrain_call
    run_hook_kohya_ss_run_file(
  File "/root/ComfyUI/custom_nodes/ComfyUI-TrainTools-MZ/mz_train_tools_core.py", line 426, in run_hook_kohya_ss_run_file
    raise Exception(f"训练失败!!! 具体报错信息请查看控制台... {e}")
Exception: 训练失败!!! 具体报错信息请查看控制台... Command '['/conda/bin/python', '/root/ComfyUI/custom_nodes/ComfyUI-TrainTools-MZ/hook_kohya_ss_run.py', '--sys_path', '/root/ComfyUI/models/minus_zone_models/train_tools/kohya_ss_lora', '--train_config_json', '{"pretrained_model_name_or_path": "/root/ComfyUI/models/checkpoints/sd_xl_base_1.0.safetensors", "max_train_steps": "15", "xformers": true, "sdpa": false, "fp8_base": false, "mixed_precision": "fp16", "cache_latents": true, "cache_latents_to_disk": true, "network_dim": "16", "network_alpha": "8", "network_module": "networks.lora", "network_train_unet_only": true, "learning_rate": "1e-5", "lr_scheduler": "cosine_with_restarts", "optimizer_type": "AdamW", "save_every_n_epochs": "5", "shuffle_caption": true, "lr_warmup_steps": "0", "save_precision": "fp16", "lr_scheduler_num_cycles": "1", "persistent_data_loader_workers": true, "no_metadata": true, "noise_offset": "0.1", "output_dir": "/root/ComfyUI/output/mz_train_workspaces/KiKi/output", "output_name": "KiKi_lora_sdxl_20240626_182017", "no_half_vae": true, "lowram": false, "dataset_config": "/root/ComfyUI/output/mz_train_workspaces/KiKi/dataset.toml", "max_train_epochs": "100"}', '--train_func', 'run_lora_sdxl', '--master_port', '60992', '--other_config_json', '{"sample_prompt": "Anya"}']' returned non-zero exit status 1.

Prompt executed in 15.24 seconds
===========================httpd.serve_forever() end=======================================


diffusers 是什么版本

**Comment by Fihade** [comment]
**### 更新 diffusers 版本之后，解决 ‘AttributeError: module 'diffusers.loaders.single_file' has no attribute 'snapshot_download'这个问题，遇到了新的问题，如下：**


===============================================
当前分支(current branch): 71e2c91330a9d866ec05cdd10584bbb962896a99(HEAD)
目标分支(target branch): 71e2c91330a9d866ec05cdd10584bbb962896a99
From https://githubfast.com/kohya-ss/sd-scripts
 * branch            71e2c91330a9d866ec05cdd10584bbb962896a99 -> FETCH_HEAD
HEAD is now at 71e2c91 Merge pull request #1230 from kohya-ss/dependabot/github_actions/crate-ci/typos-1.19.0
===========================httpd.serve_forever() start=======================================
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.3.0+cu121 with CUDA 1201 (you have 2.1.2+cu121)
    Python  3.10.14 (you have 3.10.13)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
/conda/lib/python3.10/site-packages/diffusers/models/transformers/transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
master_port = 47353
Traceback (most recent call last):
  File "/root/ComfyUI/custom_nodes/ComfyUI-TrainTools-MZ/hook_kohya_ss_run.py", line 212, in <module>
    func_map[train_func]()
  File "/root/ComfyUI/custom_nodes/ComfyUI-TrainTools-MZ/hook_kohya_ss_run.py", line 163, in run_lora_sdxl
    LOG({
  File "/root/ComfyUI/custom_nodes/ComfyUI-TrainTools-MZ/hook_kohya_ss_run.py", line 183, in LOG
    raise Exception(f"LOG failed: {resp.text}")
Exception: LOG failed: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>
<meta type="copyright" content="Copyright (C) 1996-2016 The Squid Software Foundation and contributors">
<meta http-equiv="Content-Type" CONTENT="text/html; charset=utf-8">
<title>ERROR: The requested URL could not be retrieved</title>
<style type="text/css"></style>
</head><body id=ERR_CONNECT_FAIL>
<div id="titles">
<h1>ERROR</h1>
<h2>The requested URL could not be retrieved</h2>
</div>
<hr>

<div id="content">
<p>The following error was encountered while trying to retrieve the URL: <a href="http://127.0.0.1:47353/log">http://127.0.0.1:47353/log</a></p>

<blockquote id="error">
<p><b>Connection to 127.0.0.1 failed.</b></p>
</blockquote>

<p id="sysmsg">The system returned: <i>(111) Connection refused</i></p>

<p>The remote host or network may be down. Please try the request again.</p>

<p>Your cache administrator is <a href="mailto:root?subject=CacheErrorInfo%20-%20ERR_CONNECT_FAIL&amp;body=CacheHost%3A%20mybogusproxyhostname.local%0D%0AErrPage%3A%20ERR_CONNECT_FAIL%0D%0AErr%3A%20(111)%20Connection%20refused%0D%0ATimeStamp%3A%20Wed,%2026%20Jun%202024%2010%3A25%3A54%20GMT%0D%0A%0D%0AClientIP%3A%2010.32.11.75%0D%0AServerIP%3A%20127.0.0.1%0D%0A%0D%0AHTTP%20Request%3A%0D%0APOST%20%2Flog%20HTTP%2F1.1%0AUser-Agent%3A%20python-requests%2F2.32.3%0D%0AAccept-Encoding%3A%20gzip,%20deflate,%20br%0D%0AAccept%3A%20*%2F*%0D%0AConnection%3A%20keep-alive%0D%0AContent-Type%3A%20application%2Fjson%0D%0AContent-Length%3A%2023%0D%0AProxy-Authorization%3A%20Basic%20amFydmlzLXVzZXI6cTlvQWRPcmJtZGpzMzE%3D%0D%0AHost%3A%20127.0.0.1%3A47353%0D%0A%0D%0A%0D%0A">root</a>.</p>

<br>
</div>

<hr>
<div id="footer">
<p>Generated Wed, 26 Jun 2024 10:25:54 GMT by mybogusproxyhostname.local (squid)</p>

</div>
</body></html>

!!! Exception during processing!!! 训练失败!!! 具体报错信息请查看控制台... Command '['/conda/bin/python', '/root/ComfyUI/custom_nodes/ComfyUI-TrainTools-MZ/hook_kohya_ss_run.py', '--sys_path', '/root/ComfyUI/models/minus_zone_models/train_tools/kohya_ss_lora', '--train_config_json', '{"pretrained_model_name_or_path": "/root/ComfyUI/models/checkpoints/sd_xl_base_1.0.safetensors", "max_train_steps": "15", "xformers": true, "sdpa": false, "fp8_base": false, "mixed_precision": "fp16", "cache_latents": true, "cache_latents_to_disk": true, "network_dim": "16", "network_alpha": "8", "network_module": "networks.lora", "network_train_unet_only": true, "learning_rate": "1e-5", "lr_scheduler": "cosine_with_restarts", "optimizer_type": "AdamW", "save_every_n_epochs": "5", "shuffle_caption": true, "lr_warmup_steps": "0", "save_precision": "fp16", "lr_scheduler_num_cycles": "1", "persistent_data_loader_workers": true, "no_metadata": true, "noise_offset": "0.1", "output_dir": "/root/ComfyUI/output/mz_train_workspaces/KiKi/output", "output_name": "KiKi_lora_sdxl_20240626_182551", "no_half_vae": true, "lowram": false, "dataset_config": "/root/ComfyUI/output/mz_train_workspaces/KiKi/dataset.toml", "max_train_epochs": "100"}', '--train_func', 'run_lora_sdxl', '--master_port', '47353', '--other_config_json', '{"sample_prompt": "KiKi\\n"}']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/root/ComfyUI/custom_nodes/ComfyUI-TrainTools-MZ/mz_train_tools_core.py", line 416, in run_hook_kohya_ss_run_file
    subprocess.run(
  File "/conda/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/conda/bin/python', '/root/ComfyUI/custom_nodes/ComfyUI-TrainTools-MZ/hook_kohya_ss_run.py', '--sys_path', '/root/ComfyUI/models/minus_zone_models/train_tools/kohya_ss_lora', '--train_config_json', '{"pretrained_model_name_or_path": "/root/ComfyUI/models/checkpoints/sd_xl_base_1.0.safetensors", "max_train_steps": "15", "xformers": true, "sdpa": false, "fp8_base": false, "mixed_precision": "fp16", "cache_latents": true, "cache_latents_to_disk": true, "network_dim": "16", "network_alpha": "8", "network_module": "networks.lora", "network_train_unet_only": true, "learning_rate": "1e-5", "lr_scheduler": "cosine_with_restarts", "optimizer_type": "AdamW", "save_every_n_epochs": "5", "shuffle_caption": true, "lr_warmup_steps": "0", "save_precision": "fp16", "lr_scheduler_num_cycles": "1", "persistent_data_loader_workers": true, "no_metadata": true, "noise_offset": "0.1", "output_dir": "/root/ComfyUI/output/mz_train_workspaces/KiKi/output", "output_name": "KiKi_lora_sdxl_20240626_182551", "no_half_vae": true, "lowram": false, "dataset_config": "/root/ComfyUI/output/mz_train_workspaces/KiKi/dataset.toml", "max_train_epochs": "100"}', '--train_func', 'run_lora_sdxl', '--master_port', '47353', '--other_config_json', '{"sample_prompt": "KiKi\\n"}']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/root/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/root/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/root/ComfyUI/custom_nodes/ComfyUI-TrainTools-MZ/__init__.py", line 278, in start
    return mz_train_tools_core.MZ_KohyaSSTrain_call(kwargs)
  File "/root/ComfyUI/custom_nodes/ComfyUI-TrainTools-MZ/mz_train_tools_core.py", line 518, in MZ_KohyaSSTrain_call
    run_hook_kohya_ss_run_file(
  File "/root/ComfyUI/custom_nodes/ComfyUI-TrainTools-MZ/mz_train_tools_core.py", line 426, in run_hook_kohya_ss_run_file
    raise Exception(f"训练失败!!! 具体报错信息请查看控制台... {e}")
Exception: 训练失败!!! 具体报错信息请查看控制台... Command '['/conda/bin/python', '/root/ComfyUI/custom_nodes/ComfyUI-TrainTools-MZ/hook_kohya_ss_run.py', '--sys_path', '/root/ComfyUI/models/minus_zone_models/train_tools/kohya_ss_lora', '--train_config_json', '{"pretrained_model_name_or_path": "/root/ComfyUI/models/checkpoints/sd_xl_base_1.0.safetensors", "max_train_steps": "15", "xformers": true, "sdpa": false, "fp8_base": false, "mixed_precision": "fp16", "cache_latents": true, "cache_latents_to_disk": true, "network_dim": "16", "network_alpha": "8", "network_module": "networks.lora", "network_train_unet_only": true, "learning_rate": "1e-5", "lr_scheduler": "cosine_with_restarts", "optimizer_type": "AdamW", "save_every_n_epochs": "5", "shuffle_caption": true, "lr_warmup_steps": "0", "save_precision": "fp16", "lr_scheduler_num_cycles": "1", "persistent_data_loader_workers": true, "no_metadata": true, "noise_offset": "0.1", "output_dir": "/root/ComfyUI/output/mz_train_workspaces/KiKi/output", "output_name": "KiKi_lora_sdxl_20240626_182551", "no_half_vae": true, "lowram": false, "dataset_config": "/root/ComfyUI/output/mz_train_workspaces/KiKi/dataset.toml", "max_train_epochs": "100"}', '--train_func', 'run_lora_sdxl', '--master_port', '47353', '--other_config_json', '{"sample_prompt": "KiKi\\n"}']' returned non-zero exit status 1.

Prompt executed in 18.26 seconds
===========================httpd.serve_forever() end=======================================

**Comment by wailovet** [comment]
> **### 更新 diffusers 版本之后，解决 ‘AttributeError: module 'diffusers.loaders.single_file' has no attribute 'snapshot_download'这个问题，遇到了新的问题，如下：**
> 
> =============================================== 当前分支(current branch): 71e2c91330a9d866ec05cdd10584bbb962896a99(HEAD) 目标分支(target branch): 71e2c91330a9d866ec05cdd10584bbb962896a99 From https://githubfast.com/kohya-ss/sd-scripts
> 
> * branch            71e2c91330a9d866ec05cdd10584bbb962896a99 -> FETCH_HEAD
>   HEAD is now at 71e2c91 Merge pull request #1230 from kohya-ss/dependabot/github_actions/crate-ci/typos-1.19.0
>   ===========================httpd.serve_forever() start=======================================
>   WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
>   PyTorch 2.3.0+cu121 with CUDA 1201 (you have 2.1.2+cu121)
>   Python  3.10.14 (you have 3.10.13)
>   Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
>   Memory-efficient attention, SwiGLU, sparse and more won't be available.
>   Set XFORMERS_MORE_DETAILS=1 for more details
>   /conda/lib/python3.10/site-packages/diffusers/models/transformers/transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
>   deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
>   master_port = 47353
>   Traceback (most recent call last):
>   File "/root/ComfyUI/custom_nodes/ComfyUI-TrainTools-MZ/hook_kohya_ss_run.py", line 212, in 
>   func_maptrain_func
>   File "/root/ComfyUI/custom_nodes/ComfyUI-TrainTools-MZ/hook_kohya_ss_run.py", line 163, in run_lora_sdxl
>   LOG({
>   File "/root/ComfyUI/custom_nodes/ComfyUI-TrainTools-MZ/hook_kohya_ss_run.py", line 183, in LOG
>   raise Exception(f"LOG failed: {resp.text}")
>   Exception: LOG failed:
> 
> <title>ERROR: The requested URL could not be retrieved</title> <style type="text/css">
> !!! Exception during processing!!! 训练失败!!! 具体报错信息请查看控制台... Command '['/conda/bin/python', '/root/ComfyUI/custom_nodes/ComfyUI-TrainTools-MZ/hook_kohya_ss_run.py', '--sys_path', '/root/ComfyUI/models/minus_zone_models/train_tools/kohya_ss_lora', '--train_config_json', '{"pretrained_model_name_or_path": "/root/ComfyUI/models/checkpoints/sd_xl_base_1.0.safetensors", "max_train_steps": "15", "xformers": true, "sdpa": false, "fp8_base": false, "mixed_precision": "fp16", "cache_latents": true, "cache_latents_to_disk": true, "network_dim": "16", "network_alpha": "8", "network_module": "networks.lora", "network_train_unet_only": true, "learning_rate": "1e-5", "lr_scheduler": "cosine_with_restarts", "optimizer_type": "AdamW", "save_every_n_epochs": "5", "shuffle_caption": true, "lr_warmup_steps": "0", "save_precision": "fp16", "lr_scheduler_num_cycles": "1", "persistent_data_loader_workers": true, "no_metadata": true, "noise_offset": "0.1", "output_dir": "/root/ComfyUI/output/mz_train_workspaces/KiKi/output", "output_name": "KiKi_lora_sdxl_20240626_182551", "no_half_vae": true, "lowram": false, "dataset_config": "/root/ComfyUI/output/mz_train_workspaces/KiKi/dataset.toml", "max_train_epochs": "100"}', '--train_func', 'run_lora_sdxl', '--master_port', '47353', '--other_config_json', '{"sample_prompt": "KiKi\n"}']' returned non-zero exit status 1. Traceback (most recent call last): File "/root/ComfyUI/custom_nodes/ComfyUI-TrainTools-MZ/mz_train_tools_core.py", line 416, in run_hook_kohya_ss_run_file subprocess.run( File "/conda/lib/python3.10/subprocess.py", line 526, in run raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command '['/conda/bin/python', '/root/ComfyUI/custom_nodes/ComfyUI-TrainTools-MZ/hook_kohya_ss_run.py', '--sys_path', '/root/ComfyUI/models/minus_zone_models/train_tools/kohya_ss_lora', '--train_config_json', '{"pretrained_model_name_or_path": "/root/ComfyUI/models/checkpoints/sd_xl_base_1.0.safetensors", "max_train_steps": "15", "xformers": true, "sdpa": false, "fp8_base": false, "mixed_precision": "fp16", "cache_latents": true, "cache_latents_to_disk": true, "network_dim": "16", "network_alpha": "8", "network_module": "networks.lora", "network_train_unet_only": true, "learning_rate": "1e-5", "lr_scheduler": "cosine_with_restarts", "optimizer_type": "AdamW", "save_every_n_epochs": "5", "shuffle_caption": true, "lr_warmup_steps": "0", "save_precision": "fp16", "lr_scheduler_num_cycles": "1", "persistent_data_loader_workers": true, "no_metadata": true, "noise_offset": "0.1", "output_dir": "/root/ComfyUI/output/mz_train_workspaces/KiKi/output", "output_name": "KiKi_lora_sdxl_20240626_182551", "no_half_vae": true, "lowram": false, "dataset_config": "/root/ComfyUI/output/mz_train_workspaces/KiKi/dataset.toml", "max_train_epochs": "100"}', '--train_func', 'run_lora_sdxl', '--master_port', '47353', '--other_config_json', '{"sample_prompt": "KiKi\n"}']' returned non-zero exit status 1.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/root/ComfyUI/execution.py", line 151, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) File "/root/ComfyUI/execution.py", line 81, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) File "/root/ComfyUI/execution.py", line 74, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) File "/root/ComfyUI/custom_nodes/ComfyUI-TrainTools-MZ/**init**.py", line 278, in start return mz_train_tools_core.MZ_KohyaSSTrain_call(kwargs) File "/root/ComfyUI/custom_nodes/ComfyUI-TrainTools-MZ/mz_train_tools_core.py", line 518, in MZ_KohyaSSTrain_call run_hook_kohya_ss_run_file( File "/root/ComfyUI/custom_nodes/ComfyUI-TrainTools-MZ/mz_train_tools_core.py", line 426, in run_hook_kohya_ss_run_file raise Exception(f"训练失败!!! 具体报错信息请查看控制台... {e}") Exception: 训练失败!!! 具体报错信息请查看控制台... Command '['/conda/bin/python', '/root/ComfyUI/custom_nodes/ComfyUI-TrainTools-MZ/hook_kohya_ss_run.py', '--sys_path', '/root/ComfyUI/models/minus_zone_models/train_tools/kohya_ss_lora', '--train_config_json', '{"pretrained_model_name_or_path": "/root/ComfyUI/models/checkpoints/sd_xl_base_1.0.safetensors", "max_train_steps": "15", "xformers": true, "sdpa": false, "fp8_base": false, "mixed_precision": "fp16", "cache_latents": true, "cache_latents_to_disk": true, "network_dim": "16", "network_alpha": "8", "network_module": "networks.lora", "network_train_unet_only": true, "learning_rate": "1e-5", "lr_scheduler": "cosine_with_restarts", "optimizer_type": "AdamW", "save_every_n_epochs": "5", "shuffle_caption": true, "lr_warmup_steps": "0", "save_precision": "fp16", "lr_scheduler_num_cycles": "1", "persistent_data_loader_workers": true, "no_metadata": true, "noise_offset": "0.1", "output_dir": "/root/ComfyUI/output/mz_train_workspaces/KiKi/output", "output_name": "KiKi_lora_sdxl_20240626_182551", "no_half_vae": true, "lowram": false, "dataset_config": "/root/ComfyUI/output/mz_train_workspaces/KiKi/dataset.toml", "max_train_epochs": "100"}', '--train_func', 'run_lora_sdxl', '--master_port', '47353', '--other_config_json', '{"sample_prompt": "KiKi\n"}']' returned non-zero exit status 1.
> 
> Prompt executed in 18.26 seconds ===========================httpd.serve_forever() end=======================================

看起来像是xformers报错,试一下拉一下高级设置的节点,关掉xformers试试看
